### ISSUE TITLE
S5 | Redactar un resumen de las características clave de la base de datos elegida.

### ISSUE THREAD

**Issue by vittoriodurigutti** [ISPC-TST-PI-I-2024/capa-de-almacenamiento-grupo-opalo#8]
Redactar un resumen de las características clave de la base de datos elegida.
Plasmar documentacion en carpeta /almacenamiento/investigacion

**Comment by marquezjose** [comment]
Se agrega resumen de la selección de la base de datos, de acuerdo a la última reunión se definió utilizar una DB SQL por sobre la SQL por la integridad de de los datos y sensibilidad de los mismo. 

Por favor revisar e informar si hay que hacer modificaciones al documento.

Gracias.
